-- Additional Form Templates (Part 3)
-- Order Forms, Booking Forms, Application Forms

-- ORDER FORMS (8)
INSERT OR IGNORE INTO form_templates (template_name, category, description, fields, settings) VALUES

('Product Order Form', 'order', 'Simple product order form',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Product Name","name":"product","required":true},{"type":"number","label":"Quantity","name":"quantity","required":true,"min":1},{"type":"text","label":"Shipping Address","name":"address","required":true},{"type":"text","label":"City","name":"city","required":true},{"type":"text","label":"Zip Code","name":"zip","required":true},{"type":"textarea","label":"Special Instructions","name":"notes"}]',
'{"notifications":{"enabled":true}}'),

('Custom Order Form', 'order', 'Customizable product order',
'[{"type":"text","label":"Customer Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"select","label":"Product Category","name":"category","required":true,"options":["Electronics","Clothing","Home & Garden","Sports","Books","Other"]},{"type":"text","label":"Product Details","name":"product_details","required":true},{"type":"select","label":"Color","name":"color","options":["Black","White","Red","Blue","Green","Yellow","Other"]},{"type":"select","label":"Size","name":"size","options":["XS","S","M","L","XL","XXL"]},{"type":"number","label":"Quantity","name":"quantity","required":true,"min":1},{"type":"textarea","label":"Customization Notes","name":"custom"}]',
'{"notifications":{"enabled":true}}'),

('Catering Order', 'order', 'Food catering order form',
'[{"type":"text","label":"Contact Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"date","label":"Event Date","name":"event_date","required":true},{"type":"text","label":"Event Location","name":"location","required":true},{"type":"number","label":"Number of Guests","name":"guests","required":true,"min":10},{"type":"select","label":"Meal Type","name":"meal_type","required":true,"options":["Breakfast","Lunch","Dinner","Cocktail Reception","Full Day"]},{"type":"checkbox","label":"Dietary Restrictions","name":"dietary","options":["Vegetarian Options","Vegan Options","Gluten-Free","Halal","Kosher","Nut Allergies"]},{"type":"textarea","label":"Menu Preferences","name":"menu"}]',
'{"notifications":{"enabled":true}}'),

('Wholesale Order', 'order', 'Bulk wholesale order',
'[{"type":"text","label":"Company Name","name":"company","required":true},{"type":"text","label":"Contact Person","name":"contact","required":true},{"type":"email","label":"Business Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Tax ID/EIN","name":"tax_id"},{"type":"text","label":"Product SKU","name":"sku","required":true},{"type":"number","label":"Order Quantity","name":"quantity","required":true,"min":50},{"type":"text","label":"Delivery Address","name":"address","required":true},{"type":"date","label":"Required Delivery Date","name":"delivery_date"},{"type":"textarea","label":"Special Requirements","name":"requirements"}]',
'{"notifications":{"enabled":true,"priority":"high"}}'),

('Service Booking', 'order', 'Book a service appointment',
'[{"type":"text","label":"Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"select","label":"Service Type","name":"service","required":true,"options":["Consultation","Repair","Installation","Maintenance","Emergency Service"]},{"type":"date","label":"Preferred Date","name":"date","required":true},{"type":"select","label":"Time Slot","name":"time","required":true,"options":["8AM-10AM","10AM-12PM","12PM-2PM","2PM-4PM","4PM-6PM"]},{"type":"text","label":"Location/Address","name":"location","required":true},{"type":"textarea","label":"Describe the Issue","name":"description"}]',
'{"notifications":{"enabled":true}}'),

('Subscription Order', 'order', 'Monthly subscription signup',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email Address","name":"email","required":true},{"type":"select","label":"Plan Selection","name":"plan","required":true,"options":["Personal ($9.97/mo)","Family ($14.97/mo)","Business ($29.97/mo)"]},{"type":"select","label":"Billing Cycle","name":"billing","required":true,"options":["Monthly","Quarterly (Save 10%)","Annually (Save 20%)"]},{"type":"text","label":"Billing Address","name":"address","required":true},{"type":"text","label":"City","name":"city","required":true},{"type":"text","label":"Zip Code","name":"zip","required":true},{"type":"checkbox","label":"I agree to auto-renewal","name":"auto_renew","required":true,"value":"yes"}]',
'{"notifications":{"enabled":true}}'),

('Donation Form', 'order', 'Accept donations',
'[{"type":"text","label":"Donor Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"select","label":"Donation Amount","name":"amount","required":true,"options":["$10","$25","$50","$100","$250","$500","Other"]},{"type":"number","label":"Custom Amount","name":"custom_amount","min":1},{"type":"select","label":"Donation Frequency","name":"frequency","options":["One-Time","Monthly","Quarterly","Annually"]},{"type":"select","label":"Donation Purpose","name":"purpose","options":["General Fund","Specific Program","Memorial Gift","In Honor Of"]},{"type":"checkbox","label":"Make this donation anonymous","name":"anonymous","value":"yes"},{"type":"checkbox","label":"I would like to receive updates","name":"updates","value":"yes"}]',
'{"notifications":{"enabled":true}}'),

('Gift Card Purchase', 'order', 'Buy gift cards',
'[{"type":"text","label":"Your Name","name":"buyer_name","required":true},{"type":"email","label":"Your Email","name":"buyer_email","required":true},{"type":"text","label":"Recipient Name","name":"recipient_name","required":true},{"type":"email","label":"Recipient Email","name":"recipient_email","required":true},{"type":"select","label":"Gift Card Amount","name":"amount","required":true,"options":["$25","$50","$75","$100","$150","$200"]},{"type":"date","label":"Delivery Date","name":"delivery_date"},{"type":"textarea","label":"Personal Message","name":"message","maxlength":200},{"type":"select","label":"Design Theme","name":"theme","options":["Birthday","Holiday","Thank You","Congratulations","General"]}]',
'{"notifications":{"enabled":true}}'),

-- APPLICATION FORMS (8)
('Rental Application', 'application', 'Property rental application',
'[{"type":"text","label":"Full Legal Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"date","label":"Date of Birth","name":"dob","required":true},{"type":"text","label":"Current Address","name":"current_address","required":true},{"type":"number","label":"Monthly Income","name":"income","required":true},{"type":"text","label":"Employer Name","name":"employer","required":true},{"type":"text","label":"Emergency Contact Name","name":"emergency_name","required":true},{"type":"tel","label":"Emergency Contact Phone","name":"emergency_phone","required":true},{"type":"checkbox","label":"I authorize a background check","name":"background_check","required":true,"value":"yes"}]',
'{"notifications":{"enabled":true}}'),

('Loan Application', 'application', 'Apply for a loan',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Social Security Number","name":"ssn","required":true},{"type":"date","label":"Date of Birth","name":"dob","required":true},{"type":"select","label":"Loan Type","name":"loan_type","required":true,"options":["Personal Loan","Auto Loan","Home Loan","Business Loan"]},{"type":"number","label":"Requested Loan Amount","name":"amount","required":true,"min":1000},{"type":"select","label":"Employment Status","name":"employment","required":true,"options":["Employed Full-Time","Employed Part-Time","Self-Employed","Unemployed","Retired"]},{"type":"number","label":"Annual Income","name":"income","required":true},{"type":"checkbox","label":"I consent to credit check","name":"credit_check","required":true,"value":"yes"}]',
'{"notifications":{"enabled":true,"priority":"high"}}'),

('Vendor Application', 'application', 'Apply to be a vendor',
'[{"type":"text","label":"Business Name","name":"business","required":true},{"type":"text","label":"Contact Person","name":"contact","required":true},{"type":"email","label":"Business Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"url","label":"Website","name":"website"},{"type":"text","label":"Tax ID/EIN","name":"tax_id","required":true},{"type":"select","label":"Business Type","name":"business_type","required":true,"options":["Sole Proprietor","LLC","Corporation","Partnership","Non-Profit"]},{"type":"textarea","label":"Products/Services Offered","name":"offerings","required":true},{"type":"checkbox","label":"I agree to vendor terms","name":"terms","required":true,"value":"yes"}]',
'{"notifications":{"enabled":true}}'),

('Scholarship Application', 'application', 'Apply for scholarship',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"High School/College","name":"school","required":true},{"type":"select","label":"Grade Level","name":"grade","required":true,"options":["High School Senior","College Freshman","College Sophomore","College Junior","College Senior","Graduate Student"]},{"type":"number","label":"GPA","name":"gpa","required":true,"min":0,"max":4,"step":0.01},{"type":"textarea","label":"Essay: Why do you deserve this scholarship?","name":"essay","required":true,"maxlength":1000},{"type":"file","label":"Transcript","name":"transcript","accept":".pdf"},{"type":"file","label":"Letter of Recommendation","name":"recommendation","accept":".pdf"}]',
'{"notifications":{"enabled":true}}'),

('Grant Application', 'application', 'Apply for funding grant',
'[{"type":"text","label":"Organization Name","name":"organization","required":true},{"type":"text","label":"Contact Person","name":"contact","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Tax ID/EIN","name":"tax_id","required":true},{"type":"select","label":"Organization Type","name":"org_type","required":true,"options":["501(c)(3) Non-Profit","Educational Institution","Government Agency","Research Organization","Other"]},{"type":"number","label":"Requested Grant Amount","name":"amount","required":true,"min":1000},{"type":"textarea","label":"Project Description","name":"description","required":true,"rows":6},{"type":"textarea","label":"How will funds be used?","name":"usage","required":true},{"type":"file","label":"Budget Document","name":"budget","accept":".pdf,.xlsx"}]',
'{"notifications":{"enabled":true,"priority":"high"}}'),

('Speaker Application', 'application', 'Apply to speak at event',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"text","label":"Job Title","name":"title","required":true},{"type":"text","label":"Company/Organization","name":"company"},{"type":"url","label":"LinkedIn Profile","name":"linkedin"},{"type":"text","label":"Proposed Talk Title","name":"talk_title","required":true},{"type":"textarea","label":"Talk Abstract (250 words)","name":"abstract","required":true,"maxlength":250},{"type":"select","label":"Session Length","name":"duration","required":true,"options":["15 minutes","30 minutes","45 minutes","60 minutes"]},{"type":"textarea","label":"Speaker Bio (150 words)","name":"bio","required":true,"maxlength":150},{"type":"file","label":"Headshot Photo","name":"photo","accept":"image/*"}]',
'{"notifications":{"enabled":true}}'),

('Business License Application', 'application', 'Apply for business license',
'[{"type":"text","label":"Business Name","name":"business","required":true},{"type":"text","label":"Owner Name","name":"owner","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Business Address","name":"address","required":true},{"type":"text","label":"City","name":"city","required":true},{"type":"text","label":"State","name":"state","required":true},{"type":"text","label":"Zip Code","name":"zip","required":true},{"type":"select","label":"Business Type","name":"type","required":true,"options":["Retail","Food Service","Professional Services","Manufacturing","Construction","Healthcare","Other"]},{"type":"textarea","label":"Business Description","name":"description","required":true}]',
'{"notifications":{"enabled":true}}'),

('Media Credentials', 'application', 'Request media/press credentials',
'[{"type":"text","label":"Full Name","name":"name","required":true},{"type":"email","label":"Email","name":"email","required":true},{"type":"tel","label":"Phone","name":"phone","required":true},{"type":"text","label":"Media Outlet","name":"outlet","required":true},{"type":"url","label":"Outlet Website","name":"website","required":true},{"type":"text","label":"Job Title","name":"title","required":true},{"type":"select","label":"Media Type","name":"media_type","required":true,"options":["Print","Online","TV","Radio","Podcast","Freelance"]},{"type":"textarea","label":"Assignment Details","name":"assignment","required":true},{"type":"file","label":"Press Badge/ID","name":"badge","accept":"image/*,.pdf"}]',
'{"notifications":{"enabled":true}}');
